version: '{branch}-{build}'

# Force running on 'Windows Server 2016'
# when running in interactive mode (os: unstable) Windows Server 2012 R2 is used
# image: Visual Studio 2017

# See https://help.appveyor.com/discussions/questions/678-gui-unit-testing-in-appveyor
# and https://twitter.com/appveyor/status/525658624593375236
os: unstable

# py runs the latest installed version of python
# ps : Set-DisplayResolution -Width 1920 -Height 1200  (doesn't work -- including os: unstable) 
before_build:
  # set
  # pyautogui as of 0.9.41 raises exceptions when image is not found
  - py -m pip install pyautogui==0.9.38 PyScreeze==0.1.18
#  - ps: (New-Object Net.WebClient).DownloadFile("https://ci.appveyor.com/api/buildjobs/9nr2cqs0v9lp2g29/artifacts/iRIC_Offline_Installer_No_Runtime_prod-9a6400a0.exe", "$Env:APPVEYOR_BUILD_FOLDER\iRIC_Offline_Installer_No_Runtime_prod.exe")
#  - ps: (New-Object Net.WebClient).DownloadFile("https://ci.appveyor.com/api/buildjobs/bi4gvbdiixcht84j/artifacts/iRIC_Installer_181108_75a8fd8e.exe", "$Env:APPVEYOR_BUILD_FOLDER\iRIC_Offline_Installer_No_Runtime_prod.exe")
  - ps: (New-Object Net.WebClient).DownloadFile("https://ci.appveyor.com/api/buildjobs/6gkcta5ltnguf2am/artifacts/iRIC_Installer_190222_65b23451.exe", "$Env:APPVEYOR_BUILD_FOLDER\iRIC_Offline_Installer_No_Runtime_prod.exe")

build_script:
  - py run_calc.py
  - py run_iric_install.py
  - py run_iric.py
  - cd FaSTMECH\Tutorial1\Exercise1
  - py fastmech_tut1_ex1.py
  - cd ..\..\..
  - cd FaSTMECH\Tutorial2
  - py fastmech_tut2.py
  - cd ..\..
  - 7z a all-files.zip *-1024x768.png
  - 7z a all-files.zip FaSTMECH\Tutorial1\Exercise1\*-1024x768.png
  - 7z a all-files.zip FaSTMECH\Tutorial2\*-1024x768.png
  - 7z a all-files.zip Nays2DH\Tutorial1\*-1024x768.png

artifacts:
  - path: all-files.zip
